name: flutter_agenda
description: Agenda view package with diagnol scrolling, vertical timeline, horizontal resources and auto rendering for thier appoiments.
version: 3.1.0
homepage: https://github.com/iliyass-zamouri/flutter_agenda

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
